# Andrew Sala
# MadLibs2.0
def Welcome():
    print("Enter the following requested words for a cool paragraph!\n")
    theme = int(input("Select one of the following themes:\n 1 = Pizza\n 2 = Astronaut\n 3 = Summer\n"))
# user will choose a theme out of the three given options to pick what they would like their mad lib to be about
    if theme == 1:
        PizzaPizza()
    elif theme == 2:
        Summer()
    elif theme == 3:
        Astronaut()
# after theme is picked program will ask the user to enter a certain type of word
def PizzaPizza():
    adj1 = input("Adjective:")
    nat = input("Nationality:")
    person = input("First and Last Name:")
    noun1 = input("Noun:")
    adj2 = input("Adjective:")
    noun2 = input("Noun:")
    adj3 = input("Adjective:")
    adj4 = input("Adjective:")
    plural = input("Plural Noun:")
    noun3= input("Noun:")
    number = input("Number:")
    shapes = input("Shapes:")
    food = input("Food:")
    food1 = input("Food:")
    number2 = input("Number:")
# each word is represented by a variable to which will be placed in a paragraph to make the mad lib
# after the user enters in their last word their paragraph will print
    yes = 'Pizza was invented by a {} {} chef named {}. To make a pizza you need to \ntake a lump of {} and make a thin, round {} {} Then you cover it with {}, sauce\n{}, cheese, and fresh chopped {}. Next you have to bake it\nin a very hot {}. When it is done cut it into {}, {} Some kids like {} pizza the best, but my\nfavorite is the {} pizza. If I could, I would eat pizza {} times a day!\n'.format(adj1, nat, person, noun1, adj2, noun2, adj3, adj4, plural, noun3, number, shapes, food, food1, number2)
    print(yes)
    wf = open('madlibs.txt', 'a')
    wf.write(yes)
    wf.write('\n')
    wf.close()
# the paragraph will then print to a file and save it there
def Summer():
    name = input("First Name:")
    place = input("Place:")
    adj = input("Adjective:")
    plural = input("Plural Noun:")
    adj2 = input("Adjective:")
    plural2 = input("Plural Noun:")
    place1 = input("Place:")
    act = input("Action Verb:")
    plu= input("Plural Noun:")
    plu2 = input("Plural Noun:")
    ooun = input("Noun:")
    actv = input("Action Verb:")
    verbact = input("Action Verb:")
    adje = input("Adjective:")
# repeat the above 3 times for the same results in each theme
    yea = "Last summer, my mom and dad took me and {} on a trip to {}. The weather there is very\n{}! Northern {} has many {} and they make {} {} there. Many people\nalso go to {} to {} or see the {}. The people that live there\nlove to eat {} and are very proud of their big {}. They also like\nto {} in the sun and swim in the {}! It was a really {} trip!\n".format(name, place, adj, place, plural, adj2, plural2, place1, act, plu, plu2, ooun, actv, verbact, adje)
    print(yea)
    wf = open('madlibs.txt', 'a')
    wf.write(yea)
    wf.write('\n')
    wf.close()
def Astronaut():
    verbing = input("Verb Ending -ing:")
    verb = input("Verb:")
    vehicle = input("Vehicle:")
    verb1 = input("Verb:")
    tools = input("Tools:")
    nouns = input("Plural Noun:")
    color = input("Color:")
    adj = input("Adjective:")
    color1 = input("Color:")
    number = input("Number:")
    bod = input("Body Part:")
    bod1 = input("Body Part:")
    verby = input("Verb:")
    verb5 = input("Verb:")
    vehicle1 = input("Vehicle:")
    place = input("Place:")
    verb9 = input("Verb:")
    yed = "Instead of {} every day to an office, I want to {} to \nouter space on a {} for my job. I'd {} science experiments using {} and {}, and get \nto see {} holes and {} stars up close. Maybe I'd even get to meet and alien life form, with {} skin \nand  {} {} and {}. When it's time to {} to Earth I'll {} in a {}, and \nland safely in a {} where friends and family will {} me and welcome me home.\n".format(verbing, verb, vehicle, verb1, tools, nouns, color, adj, color1, number, bod, bod1, verby, verb5, vehicle1, place, verb9)
    print(yed)
    wf = open('madlibs.txt', 'a')
    wf.write(yed)
    wf.write('\n')
    wf.close()
Welcome()
